[package]
name = "rt"
version = "0.1.0"
authors = ["Kaifas Stromai <cephastorm@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.12"
